# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sqlite-oc-test' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for sqlite-oc-test
  
  #  'sqlite3', '~> 3.24.0
  pod 'sqlite3', '~> 3.24.0'

  target 'sqlite-oc-testTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sqlite-oc-testUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
